FORMAT: 1A
HOST: https://questionerv2-blair-heroku.herokuapp.com/api/v2

# Questioner-API-V2

Questioner is a crowd-source questions for a meetup. It helps the meetup organizer prioritize questions to be answered. Other users can vote on asked questions and they bubble to the top or to the bottom of the log.

## Sign up Collection [/auth/signup]

### User can sign up[POST]

A user can create an account using this action
It takes a JSON object containing a firstname, lastname, phoneNumber, username, username, email, password, confirmpassword  authorization details.

+ firstname (required, string) - first name
+ lastname (required, string) - last name
+ phoneNumber (required, integer) - phone number
+ username (required, string) - username
+ email (required, string) - user email
+ password (required, string) - Strong login password
+ confirmpassword (required, string) - Strong login confirm password

+ Request (application/json)

        {
                "firstname":"Tony",
                "lastname": "Andela",
                "phoneNumber":"0715096908",
                "username":"blairtheadmin",
                "email":"blair1234@gmail.com",
                "password": "Blairman1234",
                "confirmpassword":"Blairman1234"
        }


+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New  [GET]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }